config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
profiles:
  Joeys-MacBook-Pro.local:
    dotfiles:
    - f_vimrc
